# Use postgres/example user/password credentials

services:

  db:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: Filhinho1
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8081:8080
volumes:
  pgdata: